// THE WORD RECORDING LIST — every vocabulary word that still has no clip,
// in the order worth recording them.
//
// Run: node scripts/recording-list.mjs            (prints the summary)
//      node scripts/recording-list.mjs --write     (writes notes/recording-list.md)
//      node scripts/recording-list.mjs --write --all
//                                                  (also notes/recording-list-all.md,
//                                                   every remaining word, all categories)
//
// ⚠️ THIS IS NOT notes/audio-todo.md. That one is generated by
// scripts/audio-todo.mjs and covers LESSON PHRASES — the sentences inside Learn
// lessons ("Kuv hlub kuv tsev neeg heev."). This one covers the WORDS in
// src/data/vocabulary.js, which is what the flashcards, the word bank, the
// quizzes and the beginner path all play. Two different recording sessions;
// neither list contains the other's rows.
//
// ⚠️ GENERATED, NOT HAND-KEPT, for the reason audio-todo.mjs records: a missing
// clip renders as a disabled button, so the app never complains and a
// hand-written list goes stale the first time the vocabulary is edited.
//
// ⚠️ DEDUPED BY SPELLING. `txiv` is in the vocabulary five times over; that is
// ONE recording, and every entry that shares the spelling points at the same
// file. Counting entries would have you booking microphone time you do not need.

import { existsSync, writeFileSync, mkdirSync } from 'node:fs'
import { readdirSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const WRITE = process.argv.includes('--write')
const ALL = process.argv.includes('--all')
// The full native-speaker script, not the gap list — see rerecord() at the foot.
const RERECORD = process.argv.includes('--rerecord')

// The project is CommonJS to Node but the data files use `export`, so they are
// imported by file:// URL — the same trick check-path.mjs uses.
const asUrl = (p) => 'file://' + join(root, p).split('\\').join('/')
const { categories } = await import(asUrl('src/data/vocabulary.js'))
const { livePath, unitWords, orderedPath } = await import(asUrl('src/data/path.js'))
const reference = await import(asUrl('src/data/reference.js'))

// ── Does a stored audio path actually resolve to a file? ────────────────────
// src/lib/audioBase.js accepts both '/assets/audio/x.mp3' and the bare
// 'x.mp3' form, so this normalises the same way before looking on disk.
// ⚠️ POSIX SLASHES ALWAYS. join() gives backslashes on Windows, and these strings
// are read by a person and pasted into paths — a Windows-only list is a bug.
const posix = (p) => String(p || '').replace(/\\/g, '/')
const toAssetPath = (src) => {
  const s = String(src || '')
  if (!s) return null
  const web = s.startsWith('/assets/audio/') ? s.slice('/assets/audio/'.length) : s.replace(/^\//, '')
  return posix(join('assets', 'audio', web))
}
const hasClip = (src) => {
  const p = toAssetPath(src)
  return Boolean(p && existsSync(join(root, p)))
}

const slug = (s) =>
  String(s || '')
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, '-')
    .replace(/^-|-$/g, '')

// Where a new clip should live, and the exact string to paste into the entry's
// `audioFile`. The existing vocabulary clips use this shape.
const filePathFor = (word) => `assets/audio/vocabulary/${word.category}/${slug(word.hmongRPA)}.mp3`
const audioFieldFor = (word) => `vocabulary/${word.category}/${slug(word.hmongRPA)}.mp3`

// ── The alphabet, checked rather than assumed ───────────────────────────────
const alphabet = [
  ['Consonants', reference.consonants],
  ['Vowels', reference.vowels],
  ['Tones', reference.tones],
]
const alphabetGaps = alphabet.map(([name, items]) => {
  const missing = items.filter((i) => !hasClip(i.audio))
  return { name, total: items.length, missing }
})

// ── Which categories a Learn lesson teaches ─────────────────────────────────
// Read with a regex rather than by importing src/data/lessons.js: that file
// imports its lessons WITHOUT file extensions, which Metro resolves and Node
// does not (ERR_MODULE_NOT_FOUND). A category a lesson teaches is a category
// whose words a learner is sent to study, so it ranks above one nothing points at.
const lessonCategories = new Set()
for (const f of readdirSync(join(root, 'src/data/lessons'))) {
  const m = readFileSync(join(root, 'src/data/lessons', f), 'utf8').match(/^\s*vocab:\s*'([^']+)'/m)
  if (m) lessonCategories.add(m[1])
}

// ── The words ───────────────────────────────────────────────────────────────
const catById = new Map(categories.map((c) => [c.id, c]))
const allWords = categories.flatMap((c) => c.words.map((w) => ({ ...w, categoryTitle: c.title })))

// Deduped by spelling — ONE clip per spelling, wherever the spelling appears.
//
// ⚠️ THE OWNING ENTRY IS NOT SIMPLY THE FIRST ONE. `kuv` is in both `pronouns`
// and `relatives`; `rau` is "six" in `numbers` and "to put on (shoes)" in
// `wear-verbs`. Whichever entry owns the spelling decides the file path, so the
// owner is chosen by how prominent its category is — a category the beginner
// path teaches, then one a Learn lesson teaches, then anything else. Otherwise
// a path word's clip files itself under a category the course never opens.
//
// (Homographs are one recording on purpose: `rau` six and `rau` to-put-on are
// the same syllable said the same way. Both entries point at the one file.)
const pathCategories = new Set(orderedPath().flatMap((u) => u.categories || []))
const rank = (w) => (pathCategories.has(w.category) ? 0 : lessonCategories.has(w.category) ? 1 : 2)

const bySpelling = new Map()
for (const w of allWords) {
  const key = String(w.hmongRPA || '').trim().toLowerCase()
  if (!key) continue
  const held = bySpelling.get(key)
  if (!held) bySpelling.set(key, { word: w, alsoIn: new Set() })
  else if (rank(w) < rank(held.word)) {
    held.alsoIn.add(held.word.categoryTitle)
    held.word = w
  } else held.alsoIn.add(w.categoryTitle)
}
const needsClip = [...bySpelling.values()].filter((e) => !hasClip(e.word.audioFile))

const rowsFor = (words) =>
  words
    .map((w) => {
      const e = bySpelling.get(String(w.hmongRPA).trim().toLowerCase())
      return e && !hasClip(e.word.audioFile) ? e : null
    })
    .filter(Boolean)

const table = (entries) => {
  const out = ['| ✓ | Hmong | English | file to create |', '|---|---|---|---|']
  for (const e of entries) {
    const eng = String(e.word.english || '').split(/[·;]/)[0].trim().replace(/\|/g, '/')
    out.push(`| ☐ | **${e.word.hmongRPA}** | ${eng} | \`${filePathFor(e.word)}\` |`)
  }
  return out.join('\n')
}

// ── Report ──────────────────────────────────────────────────────────────────
const live = livePath()
const seenInPath = new Set()
const unitSections = []
let pathMissing = 0
for (const unit of live) {
  const words = unitWords(unit)
  const missing = rowsFor(words).filter((e) => {
    const key = String(e.word.hmongRPA).trim().toLowerCase()
    if (seenInPath.has(key)) return false // an earlier unit already claims it
    seenInPath.add(key)
    return true
  })
  words.forEach((w) => seenInPath.add(String(w.hmongRPA).trim().toLowerCase()))
  pathMissing += missing.length
  unitSections.push({ unit, total: words.length, missing })
}

const catGaps = categories
  .map((c) => {
    const missing = rowsFor(c.words)
    return { cat: c, total: c.words.length, missing: missing.length, taught: lessonCategories.has(c.id) }
  })
  .filter((r) => r.missing > 0)
  .sort((a, b) => Number(b.taught) - Number(a.taught) || b.missing - a.missing)

const lines = []
const P = (s = '') => lines.push(s)

P('# Voice recording list — words')
P()
P(`Generated by \`node scripts/recording-list.mjs --write\` on ${new Date().toISOString().slice(0, 10)}.`)
P('Re-run it after recording: rows disappear as the files appear on disk.')
P()
P('**Lesson phrases are a different list** — see `notes/audio-todo.md`')
P('(`node scripts/audio-todo.mjs --write`). This file is the vocabulary words.')
P()

P('## The alphabet — already done')
P()
P('| set | recorded |')
P('|---|---|')
for (const a of alphabetGaps) {
  P(`| ${a.name} | ${a.total - a.missing.length} / ${a.total}${a.missing.length ? ' ⚠️' : ' ✅'} |`)
}
P()
for (const a of alphabetGaps) {
  if (a.missing.length) {
    P(`⚠️ **${a.name} still missing:** ${a.missing.map((i) => i.letter || i.marker || '(mid)').join(', ')}`)
    P()
  }
}
P('Consonants, vowels and tones all play today, including the quadruple clusters')
P('and the mid tone. Nothing in the alphabet needs recording.')
P()

P('## Priority 1 — the beginner path')
P()
P(`The course, in teaching order: **${pathMissing} clips** over ${live.length} live units.`)
P('These are the words a new learner meets first, so they are worth recording first.')
P('Greetings and You & Me are the free units — the ones that have to sell the app.')
P()
const notLive = orderedPath().filter((u) => !live.some((l) => l.id === u.id))
if (notLive.length) {
  P(`Unit numbers skip ${notLive.map((u) => `${u.order} (${u.title})`).join(', ')}:`)
  P('not live yet (see `node scripts/check-path.mjs`), so those words are in Priority 2.')
  P()
}
for (const s of unitSections) {
  const done = s.total - s.missing.length
  P(`### ${s.unit.order}. ${s.unit.title}${s.unit.free ? ' — FREE' : ''}  (${s.missing.length} to record, ${done}/${s.total} done)`)
  P()
  if (!s.missing.length) P('✅ Every word in this unit has a clip.')
  else P(table(s.missing))
  P()
}

P('## Priority 2 — the rest of the vocabulary, by category')
P()
P(`${needsClip.length} distinct spellings have no clip, across ${catGaps.length} categories.`)
P('**Taught** marks a category a Learn lesson sends the learner to study — those')
P('words are already on a teaching path, so they earn a clip before the rest.')
P()
P('| category | to record | of | taught by a lesson |')
P('|---|---|---|---|')
for (const r of catGaps) {
  P(`| ${r.cat.title} | ${r.missing} | ${r.total} | ${r.taught ? '✅' : '' } |`)
}
P()
P('Run with `--all` to write every one of these words out as tick-box tables')
P('(`notes/recording-list-all.md`).')
P()

P('## How to add a clip')
P()
P('1. Record the word on its own, normally spoken. One word per file, mp3.')
P('2. Save it at the path in the table, e.g. `assets/audio/vocabulary/colors/liab.mp3`.')
P('3. Set the entry\'s `audioFile` in `src/data/vocabulary.js` to the same path')
P('   without the `assets/audio/` prefix — e.g. `audioFile: \'vocabulary/colors/liab.mp3\'`.')
P('4. `node scripts/generate-audio-map.js` — Metro needs a literal `require()` per')
P('   file, so a clip that is not in `src/lib/audioMap.js` will not play.')
P('5. `node scripts/recording-list.mjs --write` to refresh this list.')
P()

const report = lines.join('\n')

if (WRITE) {
  writeFileSync(join(root, 'notes/recording-list.md'), report + '\n')
  console.log('wrote notes/recording-list.md')
  if (ALL) {
    const all = ['# Voice recording list — every remaining word', '']
    for (const r of catGaps) {
      all.push(`## ${r.cat.title}  (${r.missing})`, '')
      all.push(table(rowsFor(r.cat.words)), '')
    }
    writeFileSync(join(root, 'notes/recording-list-all.md'), all.join('\n') + '\n')
    console.log('wrote notes/recording-list-all.md')
  }
}

console.log(
  [
    `alphabet:      ${alphabetGaps.map((a) => `${a.name} ${a.total - a.missing.length}/${a.total}`).join(', ')}`,
    `path words:    ${pathMissing} to record`,
    `all words:     ${needsClip.length} distinct spellings to record, ${catGaps.length} categories`,
    `lesson phrases: see notes/audio-todo.md`,
  ].join('\n')
)

// ════════════════════════════════════════════════════════════════════════════
// --rerecord — THE SCRIPT FOR A NATIVE-SPEAKER SESSION
// ════════════════════════════════════════════════════════════════════════════
//
// The default mode above lists what has NO clip. This mode lists what is being
// recorded again from scratch by a native speaker (2026-09-22): the 315 existing
// clips were a placeholder voice, and a language app's audio is worth what the
// voice on it is worth.
//
// ⚠️ IT IS DELIBERATELY NOT "EVERYTHING". The whole vocabulary is 1,259
// spellings — four or five hours at the microphone, and most of it is lookup
// words for the reader that nobody is taught. The author's brief was "the most
// relevant words in the most relevant modules", so SESSION_1 below is the
// alphabet plus the ten modules that the taught screens actually read from.
// Everything else is counted at the end and left for later, when a voice is
// already proven rather than being chosen.
//
// ⚠️ NEW CLIPS OVERWRITE THE OLD PATHS. The author's decision, and the cheap
// one: no `audioFile` edits, no audio-map regeneration, nothing to switch on — a
// new file at a known path just plays. The cost is that it destroys the old take
// on contact, so the originals were copied to archive/2026-09-22-audio-v1/
// FIRST. Do not delete that until the new set has been heard on a device.
//
// ⚠️ A ROW IS MARKED `overwrite` OR `new`, and they fail differently. A missed
// `new` row is a silent button. A missed `overwrite` row leaves the OLD VOICE in
// the app beside the new one — that is the mixed-voice failure to check for at
// the end of a session.
//
// ⚠️ WHITE HMONG (Hmoob Dawb). The vocabulary's RPA is written in it and
// `dialect_preference` defaults to 'white', so a Green recording would not match
// its own text. A Green set later needs its own paths, not these.

// The modules, in the order the author asked for them. `id` is a category id in
// src/data/vocabulary.js; `why` is what the clip is FOR, so a future cut has the
// argument rather than just the list.
const SESSION_1 = [
  { id: 'pronouns', why: 'Unit 2 of the path, and the Reference grammar tab\'s first table.' },
  { id: 'demonstratives', why: 'Points at things — taught beside the pronouns.' },
  { id: 'family-male-perspective', why: 'Unit 4 of the path. No audio at all today.' },
  { id: 'classifiers', why: 'Unit 5. Hmong cannot count without them.' },
  { id: 'verbs', why: 'Unit 8, and the sentence builder leans on them.' },
  { id: 'question-words', why: 'How a learner asks anything.' },
  { id: 'conjunctions', why: 'Joins two clauses — the step up from single sentences.' },
  { id: 'descriptions', why: 'Unit 7 of the path. No audio at all today.' },
  { id: 'tense-markers', why: 'Grammar: Hmong marks time with these, not with endings.' },
  { id: 'yog-to-be', why: 'Grammar: "kuv yog…", the first full sentence in the course.' },
]

function rerecord() {
  const PER_MIN = 4 // rough: four single words a minute, with retakes
  const mins = (n) => `~${Math.round(n / PER_MIN)} min`

  // consonants/vowels in reference.js are flat {letter, sound, audio}; the
  // exampleWord lives on the grouped doubleConsonants/tripleConsonants lists.
  // Same letters, two lists — see MISSING_FROM_REFERENCE in lib/typingDrill.js
  // for the other place those two disagree.
  const exampleWord = new Map()
  for (const k of ['doubleConsonants', 'tripleConsonants', 'quadConsonants', 'singleVowels', 'doubleVowels']) {
    for (const i of reference[k] || []) {
      if (i.exampleWord) exampleWord.set(String(i.letter).toLowerCase(), i.exampleWord)
    }
  }

  const state = (w) => (hasClip(w.audioFile) ? 'overwrite' : 'new')
  // An existing clip keeps ITS path — that is what makes overwriting free. A
  // word with no clip gets the standard vocabulary path.
  const target = (w) => (w.audioFile ? toAssetPath(w.audioFile) : filePathFor(w))

  const wordTable = (words) => {
    const out = ['| ✓ | Hmong | English | record over this path | |', '|---|---|---|---|---|']
    for (const w of words) {
      const eng = String(w.english || '').split(/[·;]/)[0].trim().replace(/\|/g, '/')
      out.push(`| ☐ | **${w.hmongRPA}** | ${eng} | \`${target(w)}\` | ${state(w)} |`)
    }
    return out.join('\n')
  }

  // One recording per spelling, claimed in the order the modules are listed:
  // a word in two of them is recorded with the first, and the second says so.
  const claimed = new Set()
  const claim = (words) => {
    const out = []
    for (const w of words) {
      const key = String(w.hmongRPA || '').trim().toLowerCase()
      if (!key || claimed.has(key)) continue
      claimed.add(key)
      const e = bySpelling.get(key)
      out.push(e ? e.word : w)
    }
    return out
  }

  // ── the alphabet ──────────────────────────────────────────────────────────
  const alphabetSets = [
    ['Consonants', reference.consonants, (i) => i.letter],
    ['Vowels', reference.vowels, (i) => i.letter],
    ['Tones', reference.tones, (i) => `${i.marker || '(no letter)'} — ${i.name}`],
  ]
  let alphabetCount = 0
  const a = ['# Session 1a — the alphabet', '']
  a.push('Every letter and every tone the Reference tab teaches, and the first Hmong')
  a.push('anyone hears in this app. **All of these already have a clip**, so the whole')
  a.push('file is `overwrite`: the new take replaces the old one at the same path.')
  a.push('')
  a.push('Say the letter as the alphabet lessons teach it, then its example word where')
  a.push('there is one. The tone rows matter most — record those eight in one take,')
  a.push('in this order, so the pitches are relative to each other.')
  a.push('')
  for (const [name, items, label] of alphabetSets) {
    alphabetCount += items.length
    a.push(`## ${name}  (${items.length})`, '')
    a.push('| ✓ | item | example | record over this path |')
    a.push('|---|---|---|---|')
    for (const i of items) {
      const ex =
        i.exampleWord ||
        exampleWord.get(String(i.letter || '').toLowerCase()) ||
        i.example ||
        (i.sound ? `sounds like "${i.sound}"` : '')
      a.push(`| ☐ | **${label(i)}** | ${String(ex).replace(/\|/g, '/')} | \`${toAssetPath(i.audio)}\` |`)
    }
    a.push('')
  }

  // ── the ten modules ───────────────────────────────────────────────────────
  const blocks = []
  for (const m of SESSION_1) {
    const cat = catById.get(m.id)
    if (!cat) {
      console.warn(`⚠️  no such category: ${m.id} — check SESSION_1 against vocabulary.js`)
      continue
    }
    const words = claim(cat.words)
    blocks.push({ cat, why: m.why, words, dropped: cat.words.length - words.length })
  }
  const moduleCount = blocks.reduce((n, b) => n + b.words.length, 0)

  const w = ['# Session 1b — the ten core modules', '']
  w.push('The words the taught screens read from: the path\'s units, the Reference')
  w.push('grammar tables, and the sentence builder. One clip per spelling — a word')
  w.push('that appears in two modules is listed with the first one.')
  w.push('')
  w.push('⚠️ The Reference **grammar** tab has no audio of its own: its six tables are')
  w.push('drawn from these same categories (pronouns, verbs, tense markers, question')
  w.push('words, classifiers, numbers), so recording these fills that tab too.')
  w.push('')
  for (const b of blocks) {
    w.push(`## ${b.cat.title}  (${b.words.length})`, '')
    w.push(`_${b.why}_`)
    if (b.dropped) w.push(`_${b.dropped} more word(s) here are recorded with an earlier module._`)
    w.push('')
    w.push(b.words.length ? wordTable(b.words) : '_Every word here is recorded with an earlier module._', '')
  }

  // ── what is being left for later ──────────────────────────────────────────
  const rest = categories
    .map((c) => ({
      cat: c,
      words: c.words.filter((x) => !claimed.has(String(x.hmongRPA || '').trim().toLowerCase())),
    }))
    .filter((r) => r.words.length)
  const restCount = new Set(
    rest.flatMap((r) => r.words.map((x) => String(x.hmongRPA).trim().toLowerCase()))
  ).size

  // ⚠️ The lesson SENTENCES are not rebuilt here — scripts/audio-todo.mjs already
  // extracts them from the lesson data, deduped across hear/say/recall steps.
  // Two extractors of one thing is how they drift.
  const todo = existsSync(join(root, 'notes/audio-todo.md'))
    ? readFileSync(join(root, 'notes/audio-todo.md'), 'utf8')
    : ''
  const sentenceCount = (todo.match(/^\| ☐/gm) || []).length

  const l = ['# Later — what session 1 leaves out', '']
  l.push('Not a to-do list so much as an honest count. Record session 1, hear it in the')
  l.push('app, and only then decide how much more of this is worth the microphone time.')
  l.push('')
  l.push(`- **${restCount} more word spellings**, across ${rest.length} categories. The full`)
  l.push('  tables are in `notes/recording-list-all.md`')
  l.push('  (`node scripts/recording-list.mjs --write --all`).')
  l.push(`- **${sentenceCount} lesson sentences** — whole sentences from Learn lessons,`)
  l.push('  none ever recorded. They have their own generated list:')
  l.push('  `notes/audio-todo.md` (`node scripts/audio-todo.mjs --write`).')
  l.push('')
  l.push('The biggest blocks in that remainder, largest first:')
  l.push('')
  l.push('| category | words left | taught by a lesson |')
  l.push('|---|---|---|')
  for (const r of [...rest].sort((x, y) => y.words.length - x.words.length).slice(0, 12)) {
    l.push(`| ${r.cat.title} | ${r.words.length} | ${lessonCategories.has(r.cat.id) ? '✅' : ''} |`)
  }
  l.push('')
  l.push('The `reading-*` categories are the reader\'s glossary: tapped for meaning, not')
  l.push('taught, and the last thing worth a clip.')

  // ── the plan ──────────────────────────────────────────────────────────────
  const total = alphabetCount + moduleCount
  const R = []
  const p = (s = '') => R.push(s)
  p('# Re-recording with a native speaker — the session plan')
  p()
  p(`Generated by \`node scripts/recording-list.mjs --rerecord\` on ${new Date().toISOString().slice(0, 10)}.`)
  p('Re-run it any time; it reads the live data.')
  p()
  p('**Dialect: White Hmong (Hmoob Dawb)** — the vocabulary\'s RPA is written in it.')
  p()
  p('| | what | items | rough time |')
  p('|---|---|---|---|')
  p(`| [1a](session-1a-alphabet.md) | the alphabet: every letter and tone | ${alphabetCount} | ${mins(alphabetCount)} |`)
  p(`| [1b](session-1b-core-modules.md) | the ten core modules | ${moduleCount} | ${mins(moduleCount)} |`)
  p(`| | **session 1 total** | **${total}** | **${mins(total)}** |`)
  p(`| [later](later.md) | the rest of the vocabulary | ${restCount} | ${mins(restCount)} |`)
  // ×2, not ÷2: a sentence is slower than a word, read twice.
  p(`| [later](later.md) | lesson sentences | ${sentenceCount} | ${mins(sentenceCount * 2)} |`)
  p()
  p('Times assume four items a minute with retakes, and no editing. They answer')
  p('"one session or six", not "book the studio until 4pm".')
  p()
  p('## Why these modules and not the whole dictionary')
  p()
  p(`The vocabulary is ${1259} spellings. Session 1 is the ${total} items that the`)
  p('**taught** screens read from — the alphabet, the path\'s units, the Reference')
  p('grammar tables, the sentence builder. Everything left over is mostly the')
  p('reader\'s lookup glossary, which nobody is taught and which can wait until a')
  p('voice is proven rather than being chosen.')
  p()
  p('## ⚠️ Read this before the session')
  p()
  p('- **The new file goes at the same path as the old one.** No code or data')
  p('  changes; a new file at a known path just plays.')
  p('- **The originals are in `archive/2026-09-22-audio-v1/`** (315 clips) — the only')
  p('  copy. Do not delete it until the new set has been heard on a device.')
  p('- **`overwrite` vs `new` in the last column.** A missed `new` row is a silent')
  p('  button; a missed `overwrite` row leaves the OLD VOICE in the app beside the')
  p('  new one. The mixed-voice case is the one to check for at the end.')
  p('- **One item per file, mono.** Record a WAV master (48 kHz) and keep it outside')
  p('  the repo; export mp3 to the paths in the tables. The repo carries 41 MB of')
  p('  audio today.')
  p('- **A clip is the word alone** — no "the word for dog is…", no English. The')
  p('  screen supplies the context.')
  p('- **Let the final consonant be heard.** In RPA the tone IS that last letter,')
  p('  and the typing drill teaches exactly that.')
  p()
  p('## The speaker')
  p()
  p('- Get permission in writing for the recordings to ship in a paid app, and ask')
  p('  how they want to be credited (`app/about.jsx` holds the credits).')
  p('- Write down who recorded it and when, so the next person can match the voice')
  p('  instead of guessing.')
  p()
  p('## After the session')
  p()
  p('1. Drop the files in at the paths in the tables.')
  p('2. `node scripts/generate-audio-map.js` — strictly only needed for **`new`**')
  p('   rows, but always safe, and an unmapped clip is silent with no error at all.')
  p('3. `node scripts/recording-list.mjs --write` — the gap list should shrink.')
  p('4. Listen **in the app**, not in a file browser: one tone, one path word, one')
  p('   long word. Then walk a flashcard deck and a unit\'s Tones step.')
  p()
  p('## Finding a clip that still has the old voice')
  p()
  p('```sh')
  p('find assets/audio -name "*.mp3" -newermt 2026-09-22 | wc -l   # re-recorded')
  p('find assets/audio -name "*.mp3" ! -newermt 2026-09-22         # still the old voice')
  p('```')

  mkdirSync(join(root, 'notes/recording'), { recursive: true })
  const files = [
    ['README.md', R.join('\n')],
    ['session-1a-alphabet.md', a.join('\n')],
    ['session-1b-core-modules.md', w.join('\n')],
    ['later.md', l.join('\n')],
  ]
  for (const [name, text] of files) writeFileSync(join(root, 'notes/recording', name), text + '\n')

  console.log(`wrote notes/recording/ — ${files.length} files`)
  console.log(`session 1a alphabet:     ${alphabetCount}`)
  for (const b of blocks) console.log(`  ${b.cat.title.padEnd(42)} ${String(b.words.length).padStart(3)}`)
  console.log(`session 1b modules:      ${moduleCount}`)
  console.log(`SESSION 1 TOTAL:         ${total}  (${mins(total)})`)
  console.log(`left for later:          ${restCount} words + ${sentenceCount} lesson sentences`)
}

if (RERECORD) rerecord()
